kind: pipeline
type: kubernetes
name: test&build

steps:
- name: test
  image: node:10
  commands:
  - npm install
  - npm test

- name: Build and Push Docker Image
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: seljuke/seljukes-node-chat-app
    tags: latest
