language: node_js
node_js:
- '10'
before_script:  
  - export NODE_ENV=production
  - npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: seljukes-node-chat-app
  api_key:
    secure: kh9grL3OvaW+7WqdHePVH529pth8I4176pECY7hXVg95KMQr0V4LFcxhCl9plJBPorJRIz6Wx1Hkqe96ubiP4OSgdSq6GMFue0EioEKgVMYRfOKEzZI0yEWMbtXGKcmpnbXrAcdsdtYl6r6yXGmmG3smpJkLTrZQ+42lwPVMEssB8UrE+5OySJq48zMFXCnbPv4AYItPeNEgIfLwbsGO+1lyG97LvkLU8LlXjbkaMqTvLKNtRRxhSWzQ5+kRVENE4DqvssC/hqHlu5RRhfSfmbvLg8BYR7PneW9JTlv6aGLxsgNpHbt6YLn7+qHLDvHh/UCdRaR0f470bdcKJ7PasDHBVrik9kdS5JrlSEfSLCOcN/1Ua7dcmAlw2ODPOUfBWOtU3vzgyyjLt8TLiokldiDPhd/1FtYftkmZ26JcaLXanuQ++4buZYfD7jmdEreup/RvENOmfiHjF6qsKCixPXsHbDeJI7zMN6uUbKB5CXtyu4C3EhGhkLGlyZ+eQlWE0KHr0qsvo+wmsCKhXmXWjwzZDrKL4usiwwb0m2PFL/6O8a6xXxBtM5gm4tDfCY4fXKNGcNPbKkq9Vf2Wzh0DQ09ibqnkrKuFUNDlI8Qgh3SOK9bORyATlAz3mAMa3si03dNE1qp5+NVTNIa7J8kvMUBysS2VESrNZDj2Ohx/jwI=
