version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  node-tests:
    jobs:
      - test
